### ISSUE TITLE
Update Firmware issue

### ISSUE THREAD

**Issue by AvgJxmes** [justcallmekoko/ESP32Marauder#10]
While connected to SSID MarauderOTA via 192.168.4.1, whenever I try to update the firmware, i keep getting Not found:/serverIndex.

![Error](https://user-images.githubusercontent.com/56485398/75089102-5d77b800-5590-11ea-9db0-08b01e9afbed.jpg)

**Comment by AvgJxmes** [comment]
The reason why it wasn't loading was because of this <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'>

hence need to used ethernet cable to connect to the internet for the computer and then wireless join to the marauder.

**Comment by AvgJxmes** [comment]
Pls update to the latest release of the Marauder firmware currently the bin file is still 4.0. If possible can update the entire repo to the latest version?

**Comment by tobozo** [comment]
have you tried to edit [Web.cpp](https://github.com/justcallmekoko/ESP32Marauder/blob/eb492c4cb7f9a7a26a2816c24448075ca8897d1e/esp32_marauder/Web.cpp#L47) and replace `WiFi.softAP(ssid, password);` by this :

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, password);

you may need to remove these lines too:

    Serial.print("IP address: ");
    Serial.println(WiFi.softAPIP());

Explanation: instead of being an access point, your Marauder will join your WAN and be accessible via mdns (e.g. esp32.local) or IP address and will share the internet connection.

Other solution would be to bundle jquery.min.js with the SPIFFS partition and modify the HTML, but there's probably a reason why @justcallmekoko hasn't done it already (browser cache problems or the need to hardcode your gateway ssid/pass ?).

**Comment by justcallmekoko** [comment]
Not sure why, but i did not have an issue running the update from my devices while marauder was running it’s own AP. I will probably apply the solution shown in [this thread](https://esp32.com/viewtopic.php?t=11744) on the espressif forum.

**Comment by tobozo** [comment]
interesting to note that ``server.serveStatic("/js", SPIFFS, "/js"); will automatically generate the Cache-Control headers, decide whether to send the .js or .js.gz file depending on the request, and prevent the browser to mess with the stability of the webserver

**Comment by justcallmekoko** [comment]
I believe I have resolved the issue thanks to the thread I referenced earlier. Please refer to the following screenshots. During this testing, the marauder was hosting its own access point with no internet access. I will publish a new release (v0.4.5)

**Here is the login page of the update server**
![login_page](https://user-images.githubusercontent.com/25190487/75100774-5ce71d80-55a0-11ea-9084-59ad5bc5bc04.PNG)

**Here is the browse file page with an asyncwebserver warning**
![browse_file](https://user-images.githubusercontent.com/25190487/75100775-5ce71d80-55a0-11ea-8548-b8e5edf5ef77.PNG)

**File has been chosen (without reloaded the page)**
![file_chosen](https://user-images.githubusercontent.com/25190487/75100776-5ce71d80-55a0-11ea-9280-8b484b19faa1.PNG)

**Starting the update**
![update_started](https://user-images.githubusercontent.com/25190487/75100777-5d7fb400-55a0-11ea-9b8b-10700794242a.PNG)

**jquery function called**
![function_called](https://user-images.githubusercontent.com/25190487/75100778-5d7fb400-55a0-11ea-8b17-a0f01a7b7fe9.PNG)

**Update running from perspective of the marauder UI**
![IMG_2155 - Copy](https://user-images.githubusercontent.com/25190487/75100830-11813f00-55a1-11ea-9616-6fedcecf1c85.jpg)

**Update applied (with older version of marauder)**
![IMG_2156 - Copy](https://user-images.githubusercontent.com/25190487/75100831-12b26c00-55a1-11ea-84b3-66ad7fe6bd86.jpg)

**Comment by AvgJxmes** [comment]
> have you tried to edit Web.cpp and replace WiFi.softAP(ssid, password); by this :
> WiFi.mode(WIFI_STA);
> WiFi.begin(ssid, password);
> 
> you may need to remove these lines too:
> Serial.print("IP address: ");
> Serial.println(WiFi.softAPIP());
> 
> Explanation: instead of being an access point, your Marauder will join your WAN and be accessible via mdns (e.g. esp32.local) or IP address and will share the internet connection.
> Other solution would be to bundle jquery.min.js with the SPIFFS partition and modify the HTML, but there's probably a reason why @justcallmekoko hasn't done it already (browser cache problems or the need to hardcode your gateway ssid/pass ?).

done thanks.

**Comment by AvgJxmes** [comment]
> I believe I have resolved the issue thanks to the thread I referenced earlier. Please refer to the following screenshots. During this testing, the marauder was hosting its own access point with no internet access. I will publish a new release (v0.4.5)
> Here is the login page of the update server
> 
> Here is the browse file page with an asyncwebserver warning
> 
> File has been chosen (without reloaded the page)
> 
> Starting the update
> 
> jquery function called
> 
> Update running from perspective of the marauder UI
> 
> Update applied (with older version of marauder)

got it thanks for the quick reply and help. Enjoying the ESP32 Marauder now. A lot of people from office asking me where I got it.
