### ISSUE TITLE
im getting a ton of errors and notes and warnings

### ISSUE THREAD

**Issue by Irish1982** [justcallmekoko/ESP32Marauder#103]
I need help what am i doing wrong no matter what i do i get error after error i fix the error i get more
[ERRORS.txt](https://github.com/justcallmekoko/ESP32Marauder/files/7624591/ERRORS.txt)

**Comment by justcallmekoko** [comment]
What IDE are you using to build the firmware?

**Comment by Irish1982** [comment]
Arduino ide

**Comment by Irish1982** [comment]
I used wrong version of lvgl

**Comment by Irish1982** [comment]
Not that it mattered I got the same warning at the end and the list is longer

**Comment by justcallmekoko** [comment]
Would you mind copying and pasting your new errors here in a response instead of a file. Enclose the content in triple backticks like this ```

So it should look like this...

```
Errors and stuff
More errors and stuff
```

**Comment by justcallmekoko** [comment]
#97
