### ISSUE TITLE
Validate patch in arduino-esp32 2.0.2

### ISSUE THREAD

**Issue by joroMaser** [justcallmekoko/ESP32Marauder#109]
[link](https://github.com/justcallmekoko/ESP32Marauder/wiki/arduino-ide-setup#if-you-are-following-these-instructions-you-do-not-need-to-do-this)

In arduino-esp32 2.0.2 In line 33 :
`build.extra_flags.esp32=-DARDUINO_USB_CDC_ON_BOOT=0` and not `build.extra_flags.esp32=-DARDUINO_SERIAL_PORT=0`

Can you validate this will work ?

**Comment by justcallmekoko** [comment]
I have no idea what these flags are for. Why 2.0.2?

**Comment by justcallmekoko** [comment]
Moved to arduino esp32 core 2.0.3
