### ISSUE TITLE
support for m5 fire stack

### ISSUE THREAD

**Issue by gtgre** [justcallmekoko/ESP32Marauder#114]
can you please relese documentation and code for the m5 fire stack?

**Comment by 201nasko** [comment]
yes agreed!!! and or m5stack core 2 (the one im trying to port it too)

**Comment by justcallmekoko** [comment]
I am currently developing for compatibility with one of the new pieces of hardware I've designed so I will probably not be getting around to this anytime soon but you are more than welcome to take a crack at it yourself especially if you can get it working with m5stack faces

**Comment by r00sta** [comment]
@201nasko have you had much luck? I'm looking to do the same...

**Comment by 201nasko** [comment]
@r00sta i've managed to get it on my m5stack core 2 but have not yet managed to get it on my adafruit pyportal titano... ill post documenting how to do it a little later today!

**Comment by rexido1** [comment]
Who knows why this error occurs: exit status 1
'updateMenu' was not declared in this scope ?


#ifdef HAS_SCREEN
        menu_function_obj.changeMenu(updateMenu);
#endif

**Comment by justcallmekoko** [comment]
@rexido1 when was the last time you pulled from the repo?

**Comment by rexido1** [comment]
> @rexido1 when was the last time you pulled from the repo?

one day ago

**Comment by LuckyFishGeek** [comment]
@201nasko  Can you share how to make m5 fire stack? thank you very much

**Comment by justcallmekoko** [comment]
Support for M5 stack will have to be user-based. It is possible to build M5 stack compatible firmware from source. You would need to add configurations for button input and ensure the proper screen configuration is selected upon compilation.

**Comment by 7h30th3r0n3** [comment]
> @r00sta i've managed to get it on my m5stack core 2 but have not yet managed to get it on my adafruit pyportal titano... ill post documenting how to do it a little later today!

any news about m5stack core 2 documentation ? trying to make the same too 😋

**Comment by Aro2142** [comment]
I did it, but....

https://github.com/justcallmekoko/ESP32Marauder/assets/48096137/2a52c2b5-a413-4d3f-ac8c-fa9d086c3cbf

Display ILI9342C.  Probably you need to use a different driver, not for ILI9341
😁

**Comment by Aro2142** [comment]
> Display ILI9342C. Probably need to use a different driver, not for ILI9341 😁

It helped, but not much

https://github.com/justcallmekoko/ESP32Marauder/assets/48096137/7848130f-d442-46dc-a949-460fae45ec79

**Comment by Aro2142** [comment]
Any ideas?)

**Comment by 7h30th3r0n3** [comment]
> Any ideas?)

Well , on my side, I tried quite a few things, but nothing seems to work so I decided to create my own firmware

**Comment by Aro2142** [comment]
> > Any ideas?)
> 
> Well , on my side, I tried quite a few things, but nothing seems to work so I decided to create my own firmware

Yeah that's why I made this shit, but it works quite well.  Now 
![2024-02-23-22-38-20-183](https://github.com/justcallmekoko/ESP32Marauder/assets/48096137/bd390cee-5133-4b46-8b7b-da0635cc07d9)
need to assemble the Python code to make it all look nice

**Comment by Aro2142** [comment]
M5 Stack will control esp32 like flipper zero lol

**Comment by Aro2142** [comment]
Ahhhh, it doesn’t work stably, it seems that the M5stack’s power supply is not enough, even pcram stops working...

**Comment by Aro2142** [comment]
I decided to make a huge crutch for M5Stack and will soon create a GIT repository for my project. It's a terribly dumb way to get Marauder to work on the M5, but it's better than nothing.
The project name will be "M5Stack marauder helper" XD

**Comment by 7h30th3r0n3** [comment]
Maybe check the Evil-M5core2 firmware, better than nothing haha 😜

**Comment by Aro2142** [comment]
> Maybe check the Evil-M5core2 firmware, better than nothing haha 😜

I have already checked Evil-M5core2.  I hope that your project has a great future ahead, but unfortunately there is no function for sending Deauther frames yet.  If I could, I wouldn't waste time on this if I knew how to send these damn frames, but my brain isn't strong enough for that😁.

**Comment by 7h30th3r0n3** [comment]
Deauth should be implemented in near future, I got lot of demand for this functionality
