### ISSUE TITLE
Crash after attack Flipper Zero

### ISSUE THREAD

**Issue by Chaoscake** [justcallmekoko/ESP32Marauder#130]
Hey,
I'm having an issue with crashing.
Every time I  attack, it says 
wifi:sched is null, if=1 tid=7 flags=6402
wifi:trc.c rcReachRetryLimit 1733

Yes.... I'm a noob.
What did I do wrong and how can I fix it?
Thx

**Comment by justcallmekoko** [comment]
This is a duplicate issue to https://github.com/justcallmekoko/ESP32Marauder/issues/128 and has been fixed
