### ISSUE TITLE
Flipper Zero marauder - microSD not recognized

### ISSUE THREAD

**Issue by gigi944** [justcallmekoko/ESP32Marauder#132]
Hello!
it seems that the sdcard is not correctly mounted in marauder, when using the flipper zero device:

`
> #reboot
Rebooting...
ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0xc (RTC_SW_CPU_RST),boot:0x9 (SPI_FAST_FLASH_BOOT)
Saved PC:0x400265e8
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x498
load:0x4004c000,len:0xa74
load:0x40050000,len:0x25ec
entry 0x4004c194
ESP-IDF version is: v4.4-dev-2313-gc69f0ec32
Failed to mount SD Card
SD Card NOT Supported
CLI Ready

              @@@@@@
              @@@@@@@@
              @@@@@@@@@@@
             @@@@@@  @@@@@@
          @@@@@@@      @@@@@@@
        @@@@@@            @@@@@@
     @@@@@@@                @@@@@@@
   @@@@@@                      @@@@@@
@@@@@@@              @@@@@@@@@@@@@@@@
@@@@@                 @@@@@@@@@@@@@@@
@@@@@                   @@@@@@@
@@@@@                      @@@@@@
@@@@@@                       @@@@@@@
  @@@@@@                        @@@@@@@@@@@@
    @@@@@@@                          @@@@@@
       @@@@@@                     @@@@@@
         @@@@@@@                @@@@@@
            @@@@@@           @@@@@@
              @@@@@@@      @@@@@@
                 @@@@@@ @@@@@@
                   @@@@@@@@@
                      @@@@@@
                        @@@@

--------------------------------

         ESP32 Marauder

            v0.9.10

       By: justcallmekoko

--------------------------------
`

not sure if this is a known bug, I couldn't find any ref for this issue.
microSD is 16GB, class10.
I also tried with a 8GB one, with fs in FAT32 and later on in exFAT, nothing worked so far.

**Comment by justcallmekoko** [comment]
The microSD card in the flipper zero is not meant to be used by the wifi dev board. There is no direct physical connection between them.
