### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32-S2: Timed out waiting for packet header

### ISSUE THREAD

**Issue by nastea1** [justcallmekoko/ESP32Marauder#133]
I assume I'm missing the driver on the com port, it says "none on com4" or "none on com7" even though I pick the right board, etc. I've got the 2.0.0rc drivers loaded, so I"m assuming my stupid windows computer isn't loading the com drivers correctly. It lists them as microsoft drivers which I know is wrong.

A fatal error occurred: Failed to connect to ESP32-S2: Timed out waiting for packet header
Sketch uses 751246 bytes (38%) of program storage space. Maximum is 1966080 bytes.
Global variables use 32500 bytes (9%) of dynamic memory, leaving 295180 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.1
Serial port COM4
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32-S2: Timed out waiting for packet header
A fatal error occurred: Failed to connect to ESP32-S2: Timed out waiting for packet header

**Comment by justcallmekoko** [comment]
Have you tried holding the boot button, hitting the reset button, then releasing the boot button?

**Comment by nastea1** [comment]
That was it!
