### ISSUE TITLE
OTA Update doesn't save

### ISSUE THREAD

**Issue by ramondunker** [justcallmekoko/ESP32Marauder#138]
Hi,

I'm using the WiFi Development Board for the Flipper Zero. For some reason the OTA installation doesn't save after a reboot or power loss. After every reboot the firmware needs to be installed again using the web interface. Only then Marauder works.
I followed the exact guide on installing Marauder. I tried 0.9.11, 0.9.12 and 0.9.13-rc1.

Am I doing something wrong?

This is what happens when I flash the latest .bin and invoke a reboot:
![screenshot](https://i.imgur.com/Ple8V8c.png)

**Comment by ramondunker** [comment]
After trying multiple times I got it to work eventually :)

**Comment by 0raculo** [comment]
What did you did different for this to work? Tried erasing flash, multiple OTAs and nothing @ramondunker 

Thanks!
