### ISSUE TITLE
this project with new routers is useless attacks do not work now and obsolete

### ISSUE THREAD

**Issue by zagarolo** [justcallmekoko/ESP32Marauder#143]

**Comment by zagarolo** [comment]
not working in 5 ghz

**Comment by 6q6** [comment]
> not working in 5 ghz 

Esp32 Isn't compatible with 802.11 AC. 
And new routers that send out 802.11 b/g/n 9/10x supply management frames which makes deauthentication ineffective in the first place.

**Comment by justcallmekoko** [comment]
This issue is the equivalent of complaining a Tesla doesn't fly. This is a physical limitation of the ESP32 and no amount of firmware upgrades will fix this.

**Comment by zagarolo** [comment]
tell me what is it for then? hardware limitation we change hardware

**Comment by zagarolo** [comment]
all routers now and have been in ac for years

**Comment by justcallmekoko** [comment]
> 

If you change the hardware, you change the entire project since there isn't an arduino compatible MCU (that I know if) that is capable of 5ghz. So change the hardware sure but it would involve starting a completely new project, not modifying this one
