### ISSUE TITLE
Discord link doesn't work

### ISSUE THREAD

**Issue by scriptguru** [justcallmekoko/ESP32Marauder#144]
I wanted to ask a question over Discord, but the link (on the Wiki Home page) doesn't work (404).
So asking right here - would you be interested in getting rid of jQuery?
I could help with it. jQuery is not really needed here, it's used for a few things which most likely can be easily done without it.

**Comment by justcallmekoko** [comment]
Which link did you use for the discord invite?
If you have a way of accomplishing the same thing the jquery does, please feel free to submit a PR

**Comment by scriptguru** [comment]
Wiki Home page
"If you would like to chat with me and the rest of the community directly,
head over to my [discord](https://discord.gg/invite/w5JmasxvKA)."

**Comment by justcallmekoko** [comment]
New invite link posted in wiki
