### ISSUE TITLE
Sniff PMKID not working

### ISSUE THREAD

**Issue by Tinu94** [justcallmekoko/ESP32Marauder#151]
When I run Sniff PMKID it just says ''Reaceived Eapol:''. 
No PMKID information is displayed. 
What is the problem?

Specifications:
- WiFi Devboard for Flipper Zero
- ESP32Marauder v0.9.15 
- Flipper Zero Eng1n33r un1-0f6f9a

**Comment by justcallmekoko** [comment]
Duplicate to #147

**Comment by Tinu94** [comment]
Okay Thx! 
That means if I attach the SD card modification, it works?

**Comment by justcallmekoko** [comment]
That is correct
