### ISSUE TITLE
Wrong link to "Do It Yourself" at "About" article

### ISSUE THREAD

**Issue by undermuz** [justcallmekoko/ESP32Marauder#164]
![image](https://user-images.githubusercontent.com/6875507/199063183-5ace49a6-72d2-476a-b87e-da74790a6ac4.png)

The https://github.com/justcallmekoko/ESP32Marauder/wiki/do-it-yourself link opens home page with this message:
![image](https://user-images.githubusercontent.com/6875507/199063431-e81a47c8-921a-4f68-80c4-36b70a21ebf4.png)

**Comment by justcallmekoko** [comment]
No longer offering a "Do it yourself" document. The info has been moved to "Hardware" and "Getting Started"
