### ISSUE TITLE
Flipper Zero Marauder (dev board) Unable to Deauth and then send beacon frames

### ISSUE THREAD

**Issue by Archimedes127** [justcallmekoko/ESP32Marauder#166]
Hardware and firmware
Flipper Zero - Unleashed 
FZ Dev Board - Marauder v0.9.17

The dev board running marauder requires resetting after sending deauth frames and switching to beacon frames.  If the board is not reset, the flipper dev board does show that it sending beacon frames (led indicator turns red) however utilising a mobile device to scan for the beacons brings back no results. If the board is reset and beacon frames are re-sent the beacons are visible after scanning.  

1. Go to "SSID" <add name> create the name of required ssid
2. Go to scanap
3. Start scanap, ap's are visible and stored in list 
4. Open AP list. Confirm AP 
5. Select AP via "select" 
6. Carry out "attack" (deauth) on selected ap
7. Stop attack
8. Go to "Beacon Spam" <ssid list> click to start. 
9. No beacons are displayed on WiFi monitoring device (in this case mobile phone) 

**Expected behavior**
A deauth attack followed by a beacon spam afterwards without having to reset the devboard between changing.  

**Screenshots**

![image](https://user-images.githubusercontent.com/113886709/200203509-b92c2525-8304-462f-badf-a71717d3e01f.png)

![image](https://user-images.githubusercontent.com/113886709/200203537-f73f3255-eae0-479a-a16c-88152c2da4fa.png)

![image](https://user-images.githubusercontent.com/113886709/200203587-5896ef75-296a-467f-b208-e1a228db5444.png)

![image](https://user-images.githubusercontent.com/113886709/200203645-3a359743-57d4-48c8-be9a-6e5d9188a4f3.png)

No ssid shown when looking for ap's via phone (reset of board required, and it is possible) 

![image](https://user-images.githubusercontent.com/113886709/200203708-f68b108b-1a65-4d71-81f6-8631c75d97e6.png)

After emulating the issue, it was noticed that no further actions can be taken without resetting the devboard. The initial deauth attack appears to stop further pen testing.

**Comment by Archimedes127** [comment]
Double posted deauth pic. Should've been beacon spam (cut me some slack, jetlag is real)

![image](https://user-images.githubusercontent.com/113886709/200204151-ef98b77f-2b64-4bfb-a073-f3e65fd3b873.png)

**Comment by Archimedes127** [comment]
After a deauth is carried out, if you try to attack via Rickroll, no beacons appear. Reset the board and carry out the same attack, they show as intended.

**Comment by justcallmekoko** [comment]
I am unable to reproduce the bug myself. I followed this order of operations to reproduce the issue on my end. Please let me know if there was something I misunderstood.

1. `scanap`
2. `stopscan`
3. `ssid -a -g 3`
4. `select -a <index of target ap>`
5. `attack -t beacon -l` (first beacon spam)
6. `stopscan`
7. `attack -t deauth`
8. `stopscan`
9. `attack -t beacon -l`
10. `stopscan`
11. `attack -t rickroll`
12. `stopscan`

All beacon spam attacks following the deauthentication attack executed as expected. This was tested on a Marauder Mini and Flipper Zero Dev Board as the transmitter. I monitored the attacks with a separate Marauder. All of the attacks were detected by the monitoring Marauder.

**Comment by Archimedes127** [comment]
The only hardware variation is that I'm using a flipper zero/ Flipper dev board and not a marauder mini/flipper dev board as you have done above.

There must be an issue with the interface between the flipper zero and the devboard possibly. The WiFi dev board shows activity when initialised via the flipper zero (scan and attack) with green and red LEDs respectively.

**Comment by justcallmekoko** [comment]
Oh no when I say I tested this with a mini and a flipper dev board, I meant they were operating independent of each other. The flipper dev board was plugged into the flipper zero and the Marauder Mini was operating as a standalone device. Both devices performed the list of commands above and the output from both was as expected. I will need to see if there is something else I need to do to get the same thing to happen

**Comment by Archimedes127** [comment]
Can you confirm the fw versions on the FZ and Dev board? Cheers

**Comment by justcallmekoko** [comment]
I am currently running v0.9.17 on both the Marauder Mini and the Dev Board. On the FZ, I am running unleashed version unlshd-012

**Comment by Archimedes127** [comment]
I'm running unlshd-014.

I'll roll back to 012 and see if I can emulate the issue.

**Comment by justcallmekoko** [comment]
Any updates on this issue?

**Comment by Archimedes127** [comment]
None so far. Some other users have reported the same thing in some groups I'm in.  I'm trying to figure out if there's any settings/hardware variations (sd card, general flipper settings) but in all honesty I've been busy with work, so have slacked a bit regarding it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Wh331z** [comment]
I have the exact same issue as above, I am using the 0.9.1.7 Marauder OTA flashed to the flipper 0 wifi dev board, and I'm running unleashed-0.1.4. So I'm not sure if I'm doing something wrong or there's a bug in the firmware. 

Cheers

**Comment by Archimedes127** [comment]
I've ordered another dev board (dedication to the cause) to rule out it possibly being the board. I'm also going to get another FZ to rule out possible hardware issues. I expect delivery in the next week so will keep you posted.
I'm leaning towards the unleashed firmware, but as koko can't emulate the issue it almost seems like it's an intermittent thing with maybe different hardware batches? Guess we'll find out...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by justcallmekoko** [comment]
@Archimedes127 Please update to v0.10.0 when you get the chance and check if the issue is still present

**Comment by Archimedes127** [comment]
Will do mate.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Archimedes127** [comment]
Updated and issue is fixed! Good job.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Archimedes127** [comment]
So it was an issue with older versions. Good job fixing it justcallmekoko, cheers!
