### ISSUE TITLE
Diy marauder mini

### ISSUE THREAD

**Issue by skyrim55** [justcallmekoko/ESP32Marauder#178]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skyrim55** [comment]
Sir, with due respect i really love this project and respect ur work i just wanna recreat this project if is it possible to help me provide some information like what display used and some wirring diagram or schematic of "marauder mini" that caught my interest

**Comment by trisp3ar** [comment]
For what you are looking for, please see the [Marauder Mini Repo](https://github.com/justcallmekoko/MarauderMini).
It contains most of the information you are looking for. If you require schematics, please let us know. @justcallmekoko hasn't added them yet and it's prob something that has to be done in the future.
Please also use the issue form correctly.

**Comment by skyrim55** [comment]
Thanks a lot
