### ISSUE TITLE
Cant compile source code for generic ESP32, returns (.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check';

### ISSUE THREAD

**Issue by SoggyDoggy** [justcallmekoko/ESP32Marauder#181]
**Describe the bug**
Cant compile source code, returns (.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check';

**To Reproduce**
1. Use the Marauder Mini configuration with Arduino IDE 1.8.19
2. put #ifndef SD_CS before line 18 and #endif after line 69 in SDInterface.cpp
3. under Tools>Board use DOIT-ESP32-DEVKIT-V1, erase all flash before sketch upload: enabled
4. Compile the code
5. See error

**Expected behavior**
A normal compile

**Screenshots**
![image](https://user-images.githubusercontent.com/79585468/204903586-c2c203be-37b8-41b5-9854-59626b05c0cc.png)

**Marauder (please complete the following information if applicable):**

**Desktop (please complete the following information if applicable):**
 - OS: Pop_os
 - Version Latest

**Comment by justcallmekoko** [comment]
https://github.com/justcallmekoko/ESP32Marauder/wiki/arduino-ide-setup#if-you-are-following-these-instructions-you-do-not-need-to-do-this

Do this except do it for whatever hardware version of the ESP32 you're working on.
