### ISSUE TITLE
LED of FlipperZero WiFi DevBoard not working with v2.0

### ISSUE THREAD

**Issue by bkimminich** [justcallmekoko/ESP32Marauder#202]
**Describe the bug**

After flashing with [FZ_Marauder_v2.0.zip](https://github.com/UberGuidoZ/Flipper/blob/main/Wifi_DevBoard/FZ_Marauder_Flasher/FZ_Marauder_v2.0.zip) the LED of the WiFi DevBoard would no longer flash except for a short blink when plugging the board into the FZ.

Running any actions (e.g. AP scans or DeAuth attacks) would not cause the LED to shine in the intended color. 

When I downgraded the Marauder firmware to v1.7 the LED worked normally again in any mode and with the expected color.

**Comment by marcoboehrs** [comment]
Led is working again on my side. What I did in the marauder app: settings: restore -> settings: EnableLed. I think the config file was missing, because after selecting settings: restore a new one was created

**Comment by bkimminich** [comment]
This works! ❤️
