### ISSUE TITLE
Custom AP Flood/Rick Roll Message

### ISSUE THREAD

**Issue by larrymaple** [justcallmekoko/ESP32Marauder#211]
Hi there. I have an ESP32-WROOM, flashed it with the Flipper version of marauder, and use a Flipper Zero to activate it. I was wondering if there is a way to change the access points to something other than the lyrics to Never Gonna Give You Up? I'm pretty sure there isn't a .txt file I can just change it, so where in the source code can this edit be made so I can recompile it for my own use? I'd appreciate any help. Thanks.

**Comment by justcallmekoko** [comment]
You can either use this...
https://github.com/justcallmekoko/ESP32Marauder/wiki/list-beacon-spam-workflow

Or change the source code [here](https://github.com/justcallmekoko/ESP32Marauder/blob/master/esp32_marauder/WiFiScan.h#L151)
