### ISSUE TITLE
Deauthenticate

### ISSUE THREAD

**Issue by samukas81** [justcallmekoko/ESP32Marauder#221]
Deauthenticate Bluetooth clients.  After all, what is the use of only scanning Bluetooth???

**Comment by schlaf3r** [comment]
let me know if you figure that one out. bluetooth doesn't use deauthentication so be pretty hard to do. what your looking for is braktooth or sweyntooth. maybe that could be added with the addition of the nessisary hardware to be able to do bluetooth injection and l2ping

**Comment by samukas81** [comment]
The Braktooth tool would be very interesting, do you think you can implement it?
