### ISSUE TITLE
Sniffraw is not accessable in the wiki.

### ISSUE THREAD

**Issue by whois-hoeless** [justcallmekoko/ESP32Marauder#223]
**Describe the bug**
On your wiki, you are unable to access the sniffraw section. By the way, I would love to ask you some questions about the repo. By the way, I am coming from the flipper community (am support in XFW) and I have some questions regarding stations, how to scan them and how to deauth them. I basically made a guide about the most common modules which the flipper zero provides (including your app for it). Please respond to my issue here or answer to my dm (Dyiing#1682)

**To Reproduce**
If you want to reproduce the sniffraw thing just try to access the sniffraw section in the wiki.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/85312115/215626381-c8ccbce1-654d-4e85-8877-ce2003266496.png)

**Additional context**
Appreciate your work.

**Comment by napSec** [comment]
Same issue for me too

**Comment by whois-hoeless** [comment]
![image](https://user-images.githubusercontent.com/85312115/222935304-d4cf6336-8b52-47bd-9721-ea54c0cbb6b0.png)

**Comment by Wesley5n1p35** [comment]
Same
