### ISSUE TITLE
MarauderOTA access point is constantly enabled

### ISSUE THREAD

**Issue by Gooman-rus** [justcallmekoko/ESP32Marauder#234]
**Describe the bug**
When I power on my flipperzero esp32 with marauder firmware I can see MarauderOTA in the list of available access points. Is there any way to turn it off?

**Expected behavior**
MarauderOTA access point should turn on only after execution of the command `update -w`.

**Marauder (please complete the following information if applicable):**
 - Firmware version: [v0.10.1](https://github.com/justcallmekoko/ESP32Marauder/releases/tag/v0.10.1)
 - Hardware version: FlipperZero board

**Comment by MrJeems** [comment]
Are you able to connect to the Marauder software (either via serial or a Flipper Module) to successfully Scan APs?

I recently attempted to upgrade my Dev Board, but just before also happened to update my Arduino software and received board updates as well.
The OTA Flasher was written successfully, but the Marauder toolkit was only available from the time of Flash up until I removed power from the board.  As soon as I removed power it forgot the bin and reverted back to the OTA Flasher tool which enabled the access point and didn't give me access to the toolkit.
I was reading back through the documentation and it said to make sure the Board Manager was using v2.0.3 of "esp32 by Espressif Systems".  After my updates I was running v2.0.7.
I uninstalled the board from the IDE, reinstalled version 2.0.3, and re-compiled/flashed the DevBoard.
I uploaded the bin with the OTA utility and now Marauder functions as it should.

**Comment by Gooman-rus** [comment]
There is no problem with functionality of marauder firmware itself. It works fine.

I recently also noticed that when I power on the eps32 board there is no MarauderOTA access point. But when I start deauth the MarauderOTA access point is activated.

**Comment by justcallmekoko** [comment]
Fixed in v0.10.2
