### ISSUE TITLE
Is there any chance for a phishing attack?

### ISSUE THREAD

**Issue by codecolorado** [justcallmekoko/ESP32Marauder#245]
Im Fairly new on this side of tech, but I remember reading about a tool that sends a fake web page for authentication after deauth.

Would it be possible to do something like this with marauder?     
I just need a short yes or no. If this is a possibility, I'll do everything I can to make it happen, lol.

**Comment by justcallmekoko** [comment]
It would not be possible to execute this attack from a single ESP32 device as the ESP32 is unable to send broadcast deauthentication frames while serving an AP and web page...as far as I know.
