### ISSUE TITLE
Deauthor selection method 

### ISSUE THREAD

**Issue by kre8tivkulture** [justcallmekoko/ESP32Marauder#262]
I feel like the method of selecting ap and st's( [1],[2],etc.) is really cumbersome and timely. I think it would work out better to be able to just press a button and an asterisk marks your selection, similar to the dstike watches .

**Comment by justcallmekoko** [comment]
Unfortunately this is the problem with command line interfaces.  The difference between the method of the Marauder CLI and the DSTIKE watch is that the watch has switch that allow you to scroll and select things with simple movement or it even has a web UI. The Marauder CLI only accepts commands, It is not a GUI.

An alternative solution to your problem would just be to use the official Marauder hardware which features a touch screen or a 5-way tactile switch. These both allow you to just click the target you wish.
