### ISSUE TITLE
Passive pmkid sniff deauthenticates wifi clients

### ISSUE THREAD

**Issue by HanYangZhao** [justcallmekoko/ESP32Marauder#267]
**Describe the bug**
Passive pmkid 
**To Reproduce**
Assuming my wifi network is on CH1. When I run sniffpmkid -c 1, all clients will be disconnected from the AP and won't be able to reconnect until i stop running sniffpmkid. EAPOL are captured correctly

**Expected behavior**
Since it's passive mode I'm expecting clients to not be disconnected from the AP

**Screenshots**

**Marauder (please complete the following information if applicable):**
 - Firmware version: [e.g. v0.9.17] 0.10.5
 - Hardware version: [e.g. OG]  Flipper Zero with WIFI module

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by joshmuente** [comment]
I can confirm.
the PKMID Sniff is disconnecting my Phone from Wifi.

**Comment by HanYangZhao** [comment]
@joshmuente you're correct it does work as expected with ForcePMKID=disable. Is this an issue with the flipper app then?

**Comment by joshmuente** [comment]
> @joshmuente you're correct it does work as expected with ForcePMKID=disable. Is this an issue with the flipper app then?

No not really. More like a documentation issue

**Comment by ALEEF02** [comment]
Can we get more documentation on ForcePMKID and ForceProbe?
