### ISSUE TITLE
Reboot upon usb connect / disconnect

### ISSUE THREAD

**Issue by carnak** [justcallmekoko/ESP32Marauder#271]
**Describe the bug**

Anytime the usb cable between the marauder and the pc is connected / disconnected, the marauder device reboots.

**To Reproduce**
1. Simply connecting and/or disconnecting the usb cable between a pc and the marauder induces a reboot

**Expected behavior**
Don't constantly reboot

**Screenshots**

**Marauder (please complete the following information if applicable):**
 - Firmware version: v0.10.4
 - Hardware version: v4.5 

**Desktop (please complete the following information if applicable):**
 - OS: Windows
 - Putty
 - Version n/a

**Comment by Distracto069** [comment]
Same happens to me

**Comment by justcallmekoko** [comment]
This is a feature of the IP5306 charging chip and is not something that can be changed with the current hardware design.
