### ISSUE TITLE
Empty PCAP still

### ISSUE THREAD

**Issue by CyberGzuz** [justcallmekoko/ESP32Marauder#273]
Using flipper and latest xfw and the official flipper wifi dev board flashed with newest Marauder that just came out. I am still getting empty PCAPS.

**Comment by justcallmekoko** [comment]
Can you post a screenshot of your empty pcaps?

**Comment by CyberGzuz** [comment]
Let me scan-select-deauth-and scan raw- then save them and pull them. Then I’ll send pictures of what I am seeing.

**Comment by CyberGzuz** [comment]
do you want a screenshot of the file properties or uploaded in wireshark?

**Comment by CyberGzuz** [comment]
![image](https://github.com/justcallmekoko/ESP32Marauder/assets/133920247/564ece4e-44df-40dd-a2eb-d1b19cf3c251)

**Comment by CyberGzuz** [comment]
![image](https://github.com/justcallmekoko/ESP32Marauder/assets/133920247/8a378691-ab20-49b3-abd3-994c59a9f133)

**Comment by justcallmekoko** [comment]
What is the version of Marauder you are running?
What is the hardware the Marauder firmware is running on?
Is this saving to the Flipper SD or the Marauder SD?

**Comment by CyberGzuz** [comment]
10.5
on flipper zero wifi module v1 dev board from their site (no sd card)
saving to flipper sd
i used flipper.bin but i am currently trying again with serial.bin

**Comment by CyberGzuz** [comment]
i now have a pcap file lol sorry for taking your time sir and thank you for the firmware!!!
