### ISSUE TITLE
evil portal / evil twin attack

### ISSUE THREAD

**Issue by bobzen1234** [justcallmekoko/ESP32Marauder#298]
hey would it be possible to import a evil portal attack or evil twin attack to the marauder?

there is a whole github project here with the evil portal attack

https://github.com/bigbrodude6119/flipper-zero-evil-portal/tree/6b87f667ba9669c386fe00454bbef0ded7e34af1

would be a really nice feature on the marauder :)

**Comment by justcallmekoko** [comment]
Implemented

https://github.com/justcallmekoko/ESP32Marauder/wiki/evilportal
