### ISSUE TITLE
Evil Portal Login

### ISSUE THREAD

**Issue by smannchen** [justcallmekoko/ESP32Marauder#302]
**Describe the bug**
Installed latest version with Evil Portal. 
Followed Instructions and added html & config file to SD.
Started Evil Portal'
Connected successfully to access point.
No captive portal ever appears.
Can manually navigate to the portal by entering 192.168.4.1 in my browser. 

**To Reproduce**
Use Evil Portal as usual 

**Expected behavior**
Login screen pops up after connecting

**Marauder (please complete the following information if applicable):**
 - Firmware version: 0.11.0-RC1
 - Hardware version: ESP32 Marauder Kit

Devices
 - OS: Mac OS Ventura (latest non beta), IpadOS (non beta), Android 13 (Google Pixel 5)
 - Browser Chrome, Safari, Firefox

**Additional context**
Everything else functions as intended. Passwords are saved to SD.

**Comment by samukas81** [comment]
Cade os portais??

**Comment by justcallmekoko** [comment]
> **Describe the bug** Installed latest version with Evil Portal. Followed Instructions and added html & config file to SD. Started Evil Portal' Connected successfully to access point. No captive portal ever appears. Can manually navigate to the portal by entering 192.168.4.1 in my browser.


I have just applied the fix. I might go ahead and do a late night RC2 release...now. Will update this issue when the release is posted

**Comment by justcallmekoko** [comment]
Fixed
https://github.com/justcallmekoko/ESP32Marauder/releases/tag/v0.11.0-RC2
