### ISSUE TITLE
Flippers zero marauder evil portal not working );

### ISSUE THREAD

**Issue by ezpzX1** [justcallmekoko/ESP32Marauder#306]
**Describe the bug**
Whenever you try to use evil portal on the Flipper zero marauder, even with the latest firmware version on the Wi-Fi module, it says ” could not find /ap.config.txt “ I have tried putting it in the apps, data folder, and in the  route and it is still not working. I’ve asked a bunch of my friends and they can’t figure out why it’s not working either. It might be a bug or it could just be me being dumb.
**To Reproduce**

**Expected behavior**
Evil portal to function put out a SSI ID and when you click on it, it takes you to a website asking for your Google Chrome username and password
**Screenshots**

**Marauder (please complete the following information if applicable):**
 - Firmware version: [e.g. v0.9.17]
 - Hardware version: [e.g. OG] 

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by eried** [comment]
> I have tried putting it in the apps, data folder

use [apps_data](https://github.com/bigbrodude6119/flipper-zero-evil-portal/tree/main#install-the-pre-built-app-on-the-flipper)

**Comment by justcallmekoko** [comment]
Make sure you read through [this documentation](https://github.com/justcallmekoko/ESP32Marauder/wiki/evilportal) for how to use Evil Portal on Marauder.

**Comment by mikensen66** [comment]
not working for me either. if i understand correctly - some wifi dev boards have separatly integrated slots for sd cards? is it not possible to load ap.config.txt and index.html from the SD card in the flipper zero device?

**Comment by justcallmekoko** [comment]
Correct. In the documentation I sent, it states Evil Portal in Marauder requires there to be an SD card attached to the ESP32

**Comment by ezpzX1** [comment]
> the

Why? Is it not possible to add it where it's in the flippers SD card? I don't feel like many people have the SD card mod installed. Thanks
