### ISSUE TITLE
ESP32 NOT REBOOTING AFTER FIRMWARE UPDATE - mistake on bin file upload

### ISSUE THREAD

**Issue by KaminarimonOG** [justcallmekoko/ESP32Marauder#312]
**Describe the bug**
I uploaded via OTA the wrong bin file - the marauder did not reboot
after reboot the screen is black and the led are on
I am stuck
**To Reproduce**
1. Go to http://192.168.4.1/
2. install latest version (I did not use OLD.HARDWARE.BIN by mistake
4. See error - not rebooting

**Expected behavior**
device reboot with new firmware updated
**Screenshots**

**Marauder (please complete the following information if applicable):**
 - Firmware version: [e.g. v10.2 - >11]
 - Hardware version: [e.g. OG4.5 edited] 

**Desktop (please complete the following information if applicable):**
 - OS: [windows 11]
 - Browser [brave 1.57.49]

**Smartphone (please complete the following information if applicable):**

**Additional context**
I see other users experience the same issue but found no clear answer or reply

**Comment by KingGhost12** [comment]
Yeah I did the same thing last night,bricked both of them I was figuring we have to rewrite the firmware from scratch...have you found a solution i asked a few places but to no avail 
![Uploading 20231007_050840.jpg…]()

**Comment by justcallmekoko** [comment]
They are not bricked. You will need to use the spacehuhn web updater to reinstall the correct firmware
