### ISSUE TITLE
Can i update my custom wifi board through flipper zeros SD card?

### ISSUE THREAD

**Issue by V0ris3k** [justcallmekoko/ESP32Marauder#323]
I need to update my Wi-Fi board which I made using ESP 32 and I want to do it via the flipper zeros SD card. I thought that I need to just upload the newest firmware to the SD card and then just click in the marauder menu update via SD card. I already have installed the Marauder just want to update it. Thank you

**Comment by justcallmekoko** [comment]
You will either need to attach an SD card directly to your ESP32, not the flipper or you will need to use the ESP flasher on the flipper which is an entirely separate process from Marauder
