### ISSUE TITLE
Menu items on the M5StickC Plus are outside the display area

### ISSUE THREAD

**Issue by SHUR1K-N** [justcallmekoko/ESP32Marauder#324]
**Describe the bug**
The menu items are shifted so far to the left on the M5StickC Plus's LCD screen, that I can only see "th" from "Bluetooth" (I think).

**To Reproduce**
1. Install v0.11.1 on the M5StickC Plus

**Expected behavior**
The menu items being on screen.

**Marauder (please complete the following information if applicable):**
 - Firmware version: 0.11.1

**Additional context**
The menu was fine on v0.11.0-RC3.

**Comment by auburn5** [comment]
yes i have the same bug

**Comment by Fiver007** [comment]
Yeah I'm having the same error. Last version that is working for me is 10.8

**Comment by justcallmekoko** [comment]
https://github.com/justcallmekoko/ESP32Marauder/issues/341
