### ISSUE TITLE
m5stickc plus display off center

### ISSUE THREAD

**Issue by coDar12** [justcallmekoko/ESP32Marauder#330]
when i restart the device the writings doenst show up and only i can see is th of bluetooth

**Comment by MarcinBigL** [comment]
same story

**Comment by JedBartausky** [comment]
Same here

**Comment by Fiver007** [comment]
Yeah I'm having the same error. Last version that is working for me is 10.8

**Comment by justcallmekoko** [comment]
https://github.com/justcallmekoko/ESP32Marauder/issues/341
