### ISSUE TITLE
[Wiki] 'List Beacon Spam workflow' - inaccuracy on step 2

### ISSUE THREAD

**Issue by h1sfy** [justcallmekoko/ESP32Marauder#332]
**Describe the bug**
On step 2, 'list -a' doesn't work, 'list -**s**' should be used instead, since the next 'attack -t beacon -l' works with a list of ssid's, not the list of access points.

**To Reproduce**
1. Try walking through the [guide](https://github.com/justcallmekoko/ESP32Marauder/wiki/list-beacon-spam-workflow) 
2. Notice that list -a doesn't return anything, since earlier we populated a list of ssid's and not access points.

**Expected behavior**
Display your list of SSIDs to confirm they have been added

- list -s

**Marauder (please complete the following information if applicable):**
 - Firmware version: 0.12.0
 - Hardware version: OG 4,5

**Comment by justcallmekoko** [comment]
Thank you for bringing this to my attention. The wiki has just been updated
