### ISSUE TITLE
m5 stick c plus screen is fit properly

### ISSUE THREAD

**Issue by auburn5** [justcallmekoko/ESP32Marauder#334]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Marauder (please complete the following information if applicable):**
 - Firmware version: [e.g. v0.9.17]
 - Hardware version: [e.g. OG] 

**Desktop (please complete the following information if applicable):**

**Smartphone (please complete the following information if applicable):**

**Additional context**

**Comment by justcallmekoko** [comment]
https://github.com/justcallmekoko/ESP32Marauder/issues/341
