### ISSUE TITLE
CLI Update not working

### ISSUE THREAD

**Issue by armdn** [justcallmekoko/ESP32Marauder#335]
**Describe the bug**
CLI Update not working. If issue "update -w" - nothing happens. AP mode not started...

**To Reproduce**
1. Connected via minicom;
2. Send command - update -w
3. Nothing happened...

**Expected behavior**
Marauder firmware started AP mode with web-ui.

**Marauder (please complete the following information if applicable):**
 - Firmware version: since 0.11.0-RC3 to 0.12.0
 - Hardware version: Flipper Zero Wi-Fi Dev Board 

**Desktop:**
 - OS: macOS 10.14.6
 - Browser Safari
 - Version 14.1.2

In CLI:

ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40026ab1
SPIWP:0xee
mode:DIO, clock div:1
load:0x3ffe6100,len:0x498
load:0x4004c000,len:0xa74
load:0x40050000,len:0x25ec
entry 0x4004c194
E (421) esp_core_dump_flash: No core dump partition found!
E (421) esp_core_dump_flash: No core dump partition found!
ESP-IDF version is: v4.4.5
Failed to mount SD Card
SD Card NOT Supported
CLI Ready

              @@@@@@
              @@@@@@@@
              @@@@@@@@@@@
             @@@@@@  @@@@@@
          @@@@@@@      @@@@@@@
        @@@@@@            @@@@@@
     @@@@@@@                @@@@@@@
   @@@@@@                      @@@@@@
@@@@@@@              @@@@@@@@@@@@@@@@
@@@@@                 @@@@@@@@@@@@@@@
@@@@@                   @@@@@@@
@@@@@                      @@@@@@
@@@@@@                       @@@@@@@
  @@@@@@                        @@@@@@@@@@@@
    @@@@@@@                          @@@@@@
       @@@@@@                     @@@@@@
         @@@@@@@                @@@@@@
            @@@@@@           @@@@@@
              @@@@@@@      @@@@@@
                 @@@@@@ @@@@@@
                   @@@@@@@@@
                      @@@@@@
                        @@@@

--------------------------------

         ESP32 Marauder

            v0.12.0

       By: justcallmekoko

--------------------------------

> #update -w
>

**Comment by justcallmekoko** [comment]
Marauder firmware v0.12.0 no longer support OTA firmware update.
