### ISSUE TITLE
PCAP File Names to match AP

### ISSUE THREAD

**Issue by CrYoGeNiC6977** [justcallmekoko/ESP32Marauder#339]
Is it possible to auto rename/create the PCAP files when sniffing to use the name of the AP you are sniffing?  This way it would be easier to find the desired PCAP when wanting to do more with the file ;)

**Comment by justcallmekoko** [comment]
I don't believe there is a scan where you would only filter on a single AP. The most specific you can get is channel but that would s till sniff traffic from multiple APs. It would not make sense to name the PCAP after only one AP.
