### ISSUE TITLE
marauder version 0.11.1 and 0.12.0 for M5StickCPlus the "background" is not centered like version 0.11.0-RC3

### ISSUE THREAD

**Issue by scheggia500** [justcallmekoko/ESP32Marauder#341]
I don't know why but in versions 0.11.1 and 0.12.0 the "background" is not centered so it is impossible to read the writing, but this problem does not occur in versions prior to 0.11.1 and 0.12.0. any help to see if this problem can be solved or will I have to wait for subsequent versions?
![esp32](https://github.com/justcallmekoko/ESP32Marauder/assets/121356415/e96c1787-1c6d-4382-b92e-9852e27b76dd)

**Comment by Fiver007** [comment]
Yeah I'm having the same error. Last version that is working for me is 10.8

**Comment by PIckleRich22** [comment]
About to spend some time on this today but I am also having issues with the latest release. Last one properly functioning is 0.11.0-RC3

**Comment by justcallmekoko** [comment]
Fixed https://github.com/justcallmekoko/ESP32Marauder/pull/367/commits/ea097190ac0380b3067c29ed6064775875bf7263
This will be implemented in v0.13.3
