### ISSUE TITLE
Compatibility issue 

### ISSUE THREAD

**Issue by WZRDNukez** [justcallmekoko/ESP32Marauder#342]
Hello!
I was wondering if anyone could create compatibility with the ESP32s3-Box-Lite (OFW 0.5.0) with this OS?

When I try to use both 12.0 and 12.1 versions of the esp32_lbbd.bin with "Flash Download Tool 3.9.5" I get a Black Screen unable to do anything.

Hope this helps towards development!
Thanks!

**Comment by justcallmekoko** [comment]
The lddb bin was compiled for a standard ESP32, not the S3. You will need to modify the firmware and recompile to be compatible with that particular hardware but this is not something I will do myself.
