### ISSUE TITLE
Esp 32

### ISSUE THREAD

**Issue by Saad1498** [justcallmekoko/ESP32Marauder#348]
Can I use esp 32 marauder on 1.8 spi tft display?

**Comment by Nasimovy** [comment]
which controller is the display using? what resolution? what touch controller?

**Comment by justcallmekoko** [comment]
It would depend on the resolution and the display driver but it is likely supported by the TFT_eSPI library. You would have the reconfigure the screen dimensions in the code though

**Comment by Saad1498** [comment]
> It would depend on the resolution and the display driver but it is likely supported by the TFT_eSPI library. You would have the reconfigure the screen dimensions in the code though

Oh now I understand I just need to slightly change the code  then it will work. Thanks 😊
