### ISSUE TITLE
M5StickC plus screen

### ISSUE THREAD

**Issue by lowskii** [justcallmekoko/ESP32Marauder#354]
bro please fix the screen offset on m5stickcplus, also sour apple does not work

**Comment by justcallmekoko** [comment]
Need some more context and descriptive language here. "Does not work" doesn't tell me much. How does it not work? What did you do to test?

I can verify on my end that it *does* work.

Also...duplicate https://github.com/justcallmekoko/ESP32Marauder/issues/341

**Comment by lowskii** [comment]
nothing happens when I launch this attack, my iPhone feels fine)
