### ISSUE TITLE
Does not recognize or initialize SD card. 

### ISSUE THREAD

**Issue by Coach4** [justcallmekoko/ESP32Marauder#363]
Upon initial boot, does not initial SD.  Used two different San Disk 32gb card and doesn’t see either of them.  Tried with battery and without.  Please help.

**Comment by justcallmekoko** [comment]
What hardware are you running?
What firmware version are you running?

**Comment by Coach4** [comment]
Running the V6 with 0.12.1.  When I look at device info it says SD not connected.

**Comment by Coach4** [comment]
![Uploading IMG_1855.jpeg…]()

**Comment by Coach4** [comment]
Also under device info, SD Card: Not Connected.

**Comment by Coach4** [comment]
Update: Found a cheap 32gb. ONN micro at Walmart and it works beautifully now.
