### ISSUE TITLE
pmkid and sniff beacon packets have no content

### ISSUE THREAD

**Issue by LuckyFishGeek** [justcallmekoko/ESP32Marauder#370]
**Describe the bug**
When I use the sniff pmkid and sniff beacon function, I can see the sniffbeacon_x.pcap and sniffpmkid_x.pcap files saved in the sd card of the flipper zero device, but after I import them to my computer and use wireshark to check, there is no content in them, and the size is 0. The file size is 0 bytes.

**To Reproduce**
1. Scanning ap
2. Select target ap
3. sniff pmkid
4. targeted Active(list)

**Expected behavior**
capture pmkid packets.

**Screenshots**

![1](https://github.com/justcallmekoko/ESP32Marauder/assets/29472751/4495607b-f592-4fcd-8d6b-8b9bcbf4aa20)
![1](https://github.com/justcallmekoko/ESP32Marauder/assets/29472751/5fedc04c-f078-4f18-ab02-d9a887e99ce8)

**Marauder (please complete the following information if applicable):**
 - Firmware version: esp32_marauder_v0_13_3_20231026_multiboardS3
 - Hardware : esp32-s3-1u

When running the "targeted Active(list)" function, I can observe that the phone and the ap are disconnected, and when the phone is connected again, the flipper zero screen does not show that it has captured the pmkid packets, and there is no data when I enter the sdcard to view the file.

I don't know if it's a problem with the flipperzero-wifi-marauder program or the marauder firmware is not compatible with the hardware esp32-s3-1u?

Thanks again to the author and this program I learned a lot!

**Comment by 2048556128** [comment]
I'm also esp32-s3 and sniff pmkid is all out of data

**Comment by duckboyleopard** [comment]
I have the same problem, i will let you know if i find a fix

**Comment by b1scoito** [comment]
Same issue here.

**Comment by b1scoito** [comment]
Same issue here.

**Comment by b1scoito** [comment]
Found a firmware compiled by a Discord user on the Bork's S3 Multiboard Discord server, here's the link to the direct file: https://discord.com/channels/1018541151701184602/1058838888535314443/1107685977801097337, here's the link to their Discord: https://discord.com/invite/AVAeRuQTN2
