### ISSUE TITLE
Failed to open file '/ap_1.pcap'

### ISSUE THREAD

**Issue by jfiggins** [justcallmekoko/ESP32Marauder#389]
**Describe the bug**
When scanning for AP's, or when sniffing raw, getting the error: Failed to open file '/ap_1.pcap'. (When sniffing raw it's '/raw_NUM.pcap') When looking at the source code, it looks to be coming from Buffer.cpp line 140. Not 100% sure though.

**To Reproduce**
1. Go to Wifi Marauder app on Flipper Zero
2. Click on Scan
3. Wait for it to scan a couple AP's, then the errors start showing up. They repeat, it doesn't happen just once

**Expected behavior**
To be able to scan/sniff without receiving the file write error.

**Screenshots**
![Screenshot-20231115-120105](https://github.com/justcallmekoko/ESP32Marauder/assets/58125465/18a8a655-c7a6-403d-bf54-773cb484af1d)

**Marauder (please complete the following information if applicable):**
FZ Unleashed 65e 
Wifi Dev Board Pro Marauder version v.0.13.4
Companion App v0.6.3

**Additional context**
I've verified SD cart is formatted to FAT32. Was able to update via the SD card in the companion app and was successful. I've tried uploading the latest version of the companion app as well, so not an issue with the version shipped with firmware. When viewing the /ap_1.pcap file on my computer, I can see the access points in the file.

**Comment by nadja75** [comment]
Hi, can you tell me how you solved this problem, my dev-board also has the same error, even for raw sniffing files.
Thank you.

**Comment by drewdickenson** [comment]
I also am seeing this despite being able to read from the card (updated marauder via the card) and it writes data to the cap files
