### ISSUE TITLE
Include NimBLE as part of the installation documentation

### ISSUE THREAD

**Issue by justcallmekoko** [justcallmekoko/ESP32Marauder#40]
Pretty self explanatory.

**Comment by Sporksan** [comment]
Suggestion as to where we can find the library?

**Comment by justcallmekoko** [comment]
@Sporksan 
[here](https://github.com/h2zero/NimBLE-Arduino) is the library

**Comment by Sporksan** [comment]
Yeah, i should have just googled first but  thanks for pointing at the officially supported version!

**Comment by justcallmekoko** [comment]
@Sporksan 
No problem. You can never be too careful with trying to get the correct libraries. Developers can use specific forks of a well known library that can have some minor changes from the original library which make all the difference.

It's on me to include this in the documentation.

**Comment by justcallmekoko** [comment]
@tobozo I didn't even think to search for this in the library manager. Good find

**Comment by justcallmekoko** [comment]
Added to the wiki
