### ISSUE TITLE
esp32 marauder on m5stickC, not m5stickC plus

### ISSUE THREAD

**Issue by datadotlog** [justcallmekoko/ESP32Marauder#400]
Hi, i have a m5stickC and the screen is a little bit smaller, can you upload the file for stickC and not only for stickC Plus, if was possible??

Thank you

**Comment by gato001k1** [comment]
I have the already compiled version on the m5burner windows app or compile it with my github fork.
https://github.com/gato001k1/ESP32Marauder-for-m5stickc-non-plus
