### ISSUE TITLE
M5 Stickc Plus Red LED Always On

### ISSUE THREAD

**Issue by ralphiedawg** [justcallmekoko/ESP32Marauder#411]
**Describe the bug**
Red LED always on, except for when turned off, regardless of  'Enable LED'  being toggled on or off.

**To Reproduce**
1. Turn on the M5 Stickc Plus
2. Observe the LED being on

**Expected behavior**
The Led should turn off when 'Enable Led' is toggled off

**Screenshots**

**Marauder (please complete the following information if applicable):**
-Firmware Version 0.13.5
-M5Stickc Plus 1.1

**Comment by I8Pizza2Day** [comment]
same

**Comment by BIRTAX38** [comment]
Same

**Comment by cortmen** [comment]
Same
