### ISSUE TITLE
no matching function for call to 'LinkedList<String>::LinkedList()'

### ISSUE THREAD

**Issue by Dowan35** [justcallmekoko/ESP32Marauder#413]
**Describe the bug**
While trying to compile a basic esp32 wroom on arduino ide, I have this error.
line 16 in EvilPortal.cpp :   html_files = new LinkedList<String>();

(another error linked I saw: \Documents\Arduino\libraries\ESPAsyncWebServer-master\src/AsyncEventSource.h:89:59: error: 'const class LinkedList<AsyncEventSourceMessage*>' has no member named 'length')

**To Reproduce**
Connect your esp32 in reflash mode in usb, ESP32 Sketch Data Upload, Upload the esp32_marauder.ino

**Marauder (please complete the following information if applicable):**
 - Firmware version: [e.g. v0.13.5]

**Comment by 3mar7** [comment]
I have a error message While trying to compile a basic esp32 wroom on arduino ide, I have this error. No matching function for call to linkedlist<string>::linkedlist()

“Please note that I have installed the latest version of the LinkedList library.”
