### ISSUE TITLE
Can’t update marauder mini

### ISSUE THREAD

**Issue by Bullrider180** [justcallmekoko/ESP32Marauder#438]

**Comment by Bullrider180** [comment]
Mini marauder won’t update even after trying update.bin.bin

**Comment by Korthon** [comment]
The file name should say update.binNot update.bin.binSent from my iPhone On Dec 17, 2023, at 8:39 PM, Bullrider180 ***@***.***> wrote:﻿
Mini marauder won’t update even after trying update.bin.bin

**Comment by Korthon** [comment]
The file name should say update.bin
Not update.bin.bin

**Comment by Korthon** [comment]
Just name it update, it automatically populates.bin

**Comment by Gregory88PL** [comment]
If udate file has good name, Try with another memory card, I had the same problem.
