### ISSUE TITLE
avr/interrupt.h: No such file or directory ?

### ISSUE THREAD

**Issue by reckedpr** [justcallmekoko/ESP32Marauder#439]
**Describe the bug**
Whenever I try to upload (followed all steps exactly) I get an error saying avr/interrupt.h cannot be found, why is it trying to use code for avr devices!? Please help im a bit of a noob I think this is an easyish issue to fix im not smart enough to know why.

**To Reproduce**
Unsure on how to reproduce

**Expected behavior**
I expected it to compile and upload

**Screenshots**
![image](https://github.com/justcallmekoko/ESP32Marauder/assets/103007531/52e494d1-52f3-4af4-bae9-5063640aae28)

**Marauder (please complete the following information if applicable):**
Built my own, set it as v4 but I had it on v6 I changed in hopes of fixing the problem

Please help asap! Thanks

**Comment by rohanjoshy2005** [comment]
did you solve the issue i have the same issue..please reply asap
