### ISSUE TITLE
DIY ESP32 Marauder with ST7789 screen , the touchscreen ins't working

### ISSUE THREAD

**Issue by An0mXD** [justcallmekoko/ESP32Marauder#464]
i made my own esp32 marauder using a ST7789 240 x 320 screen and since i tried using it , the touchscreen doesn't work

https://github.com/justcallmekoko/ESP32Marauder/assets/50638116/29bba85b-67d7-42d2-b281-7d3202b297ba

**Comment by An0mXD** [comment]
//fixed

**Comment by kromabyte** [comment]
Hi An0mXD, can you explain how do you fixed plis ?

**Comment by grymoire** [comment]
Please tell us what you did, I have the same issue.
