### ISSUE TITLE
cheap yellow display not working

### ISSUE THREAD

**Issue by Niv1214** [justcallmekoko/ESP32Marauder#478]
cannot program the cheap yellow display . the display shows white screen . i am using the espwebtool for programing.
someone know what is the problem?

**Comment by Fr4nkFletcher** [comment]
[Try this](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display)

**Comment by Niv1214** [comment]
> [Try this](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display)

Thanks
