### ISSUE TITLE
infinite reboot in m5stickcplus

### ISSUE THREAD

**Issue by ISoloRaid** [justcallmekoko/ESP32Marauder#488]
when i turn m5stickc plus on, after the "Starting" message, the device just reboot causing an infinite loop
marauder version: 0.13.8

**Comment by Gregory88PL** [comment]
I have the same problem...

**Comment by cortmen** [comment]
unfortunately with StickCPlus reboot

**Comment by cortmen** [comment]
Any Solution for :  after the "Starting" message, the device just reboot

**Comment by bmorcelli** [comment]
Look this PR: https://github.com/justcallmekoko/ESP32Marauder/pull/499

This is how you fix the bootloop.

**Comment by ISoloRaid** [comment]
morcelli é muito pika, da nao
