### ISSUE TITLE
a list of all the html files for evil portal instead of just using index.html

### ISSUE THREAD

**Issue by CyberTechNex** [justcallmekoko/ESP32Marauder#539]
Hi, 
I was wondering if there could be a feature to choose a html file for evil portal from the files present on the sd card instead of just picking the file named index.html.

I've seen this on the flipper and was wondering if it would be possible on the esp 32 v4.

**Comment by ATOMNFT** [comment]
It is possible. I'm not sure why you can't choose other HTML files. What are running marauder on?
![17154291566285298255702533605417](https://github.com/justcallmekoko/ESP32Marauder/assets/984424/770d1c5e-58da-4896-965c-79c5c9435f6c)

**Comment by CyberTechNex** [comment]
I am using a normal esp 32 wroom with the ili9341 display. When I don't rename any file it just shows index.html not found

**Comment by justcallmekoko** [comment]
If you don't select any of the HTML files from this list shown in the picture, it defaults to "index.html"

**Comment by CyberTechNex** [comment]
Where do I select the html page in the menu, cause I just select the evil portal option.

**Comment by ATOMNFT** [comment]
> I am using a normal esp 32 wroom with the ili9341 display. When I don't rename any file it just shows index.html not found

Have you tried to go into "select EP HTML file" ?

![PXL_20240513_110518001](https://github.com/justcallmekoko/ESP32Marauder/assets/984424/c6421630-ba10-4cb7-8072-1fd1d9447e19)

**Comment by CyberTechNex** [comment]
I did not have the option before , maybe i was on an older version. I reflased using the arduino code and now everything works.

**Comment by ATOMNFT** [comment]
> I did not have the option before , maybe i was on an older version. I reflased using the arduino code and now everything works.

Glad you got it working!
