### ISSUE TITLE
White screen on TFT display

### ISSUE THREAD

**Issue by Mantas22XYT** [justcallmekoko/ESP32Marauder#586]
**Describe the bug**
The 2.8 TFT Screen is all white when booted.

**To Reproduce**
1. Connect the screen to the TFT using provided IC connections
2. Connect ESP32 to power
3. White screen

**Expected behavior**
I expect the Marauder menu to be displayed on bootup.

**Screenshots**
![image psd](https://github.com/user-attachments/assets/716919de-aaa3-4228-b392-b978cd657ead)

**Marauder (please complete the following information if applicable):**
 - Firmware version: v1.0.0
 - Hardware version: NodeMCU LDDB

**Comment by Mantas22XYT** [comment]
Nevermind I'm a fucking idiot

**Comment by pepino289** [comment]
what was the problem pls explain

**Comment by Mantas22XYT** [comment]
check if your pins are defined correctly in the display's setup.h file
