### ISSUE TITLE
How to make ttgo T8 V1.3 come with TF card interface to work？Ask for help

### ISSUE THREAD

**Issue by LuckyFishGeek** [justcallmekoko/ESP32Marauder#59]
TF card inserted into the interface on the screen can work,But in this case, the side of the screen will appear irregular and protrude.
![beauty_20201022113614](https://user-images.githubusercontent.com/29472751/96821657-f251ee80-145a-11eb-9a42-9be7d95985a1.jpg)

When I plug in the ESP32 interface, the TF card does not work
Please help me, how can I set up the TF card of ESP32 to work

The following is the schematic diagram of my configuration settings and T8 V1.3

Please save the child
![beauty_20201022113626](https://user-images.githubusercontent.com/29472751/96821925-786e3500-145b-11eb-8b2b-4b692a21c7fb.jpg)

![T8 1 3](https://user-images.githubusercontent.com/29472751/96821837-4fe63b00-145b-11eb-81a6-cae2b3f23008.jpg)

 SDIneterface.h  File configuration
#define SD_CS 12
#define SD_MOSI 23
#define SD_MISO 2
#define SD_SCK 18

**Comment by tobozo** [comment]
Can you try : 

  if (!SD.begin( 12 )) {
    Serial.println("Card Mount Failed");
  }

**Comment by LuckyFishGeek** [comment]
> Can you try :
> 
> ```c
>   if (!SD.begin( 12 )) {
>     Serial.println("Card Mount Failed");
>   }
> ```

I'll try it right away, thanks for your help

**Comment by LuckyFishGeek** [comment]
> Can you try :
> 
> ```c
>   if (!SD.begin( 12 )) {
>     Serial.println("Card Mount Failed");
>   }
> ```

The test failed. Is there any other way?

Thank you brother for your kind help

**Comment by tobozo** [comment]
The help you get has the same quality as the feedback you give :-)

First make sure that the SD Card 

  - is *correctly* inserted (not fully inserted on the pic you posted)
  - is formatted FAT32
  - doesn't have a partition that exceeds 4GB
  - isn't faulty (e.g. can be accessed correctly from another device).

Then you can try to add a pinMode() before SD.begin

```C
    int SDCardCSPin = 12;

    pinMode( SDCardCSPin, OUTPUT );  // the SD library should take care of that.
    if (!SD.begin( SDCardCSPin )) {
      Serial.println("Card Mount Failed");
    }
```

If it still doesn't work, you may try other values for SDCardCSPin (e.g. 15 is the hardware CS pin for SPI)

Where did you get those values from ?

    #define SD_CS 12
    #define SD_MOSI 23
    #define SD_MISO 2
    #define SD_SCK 18

MOSI/MISO/SCK seem to have standard values, but any TTGO example I've found uses 15 for SD_CS, maybe this pinout is for another variant of the TTGO-T8 ?

Anyway, see how [this worked](https://forum.arduino.cc/index.php?topic=594910.0) with a different model of yours, the pin numbers may be different but the logical approach to find the pins is valid.

Happy hacking !

**Comment by justcallmekoko** [comment]
It looks like the pin you have defined as `SD_CS` is not the proper pin that shows in the TTGO diagram you sent.

the CS pin of the SD card is 'DATA3' which looks like it is connected to `GPIO13` of the ESP32.

Also MOSI looks like it is connected to `GPIO15` and not `GPIO23` and SCK is connected to `GPIO14` and not `GPIO18`

So `#define SD_MISO 2` looks ok. You should just need to change `SD_MOSI`, `SD_SCK`, and `SD_CS`.

I am also curious where you got these definitions from.
```C++
#define SD_CS 12
#define SD_MOSI 23
#define SD_MISO 2
#define SD_SCK 18
```

**Comment by LuckyFishGeek** [comment]
> It looks like the pin you have defined as `SD_CS` is not the proper pin that shows in the TTGO diagram you sent.
> 
> the CS pin of the SD card is 'DATA3' which looks like it is connected to `GPIO13` of the ESP32.
> 
> Also MOSI looks like it is connected to `GPIO15` and not `GPIO23` and SCK is connected to `GPIO14` and not `GPIO18`
> 
> So `#define SD_MISO 2` looks ok. You should just need to change `SD_MOSI`, `SD_SCK`, and `SD_CS`.
> 
> I am also curious where you got these definitions from.
> 
> ```c++
> #define SD_CS 12
> #define SD_MOSI 23
> #define SD_MISO 2
> #define SD_SCK 18
> ```

Thanks for your help, I will test as you said

**Comment by LuckyFishGeek** [comment]
> The help you get has the same quality as the feedback you give :-)
> 
> First make sure that the SD Card
> 
> * is _correctly_ inserted (not fully inserted on the pic you posted)
> * is formatted FAT32
> * doesn't have a partition that exceeds 4GB
> * isn't faulty (e.g. can be accessed correctly from another device).
> 
> Then you can try to add a pinMode() before SD.begin
> 
> ```c
>     int SDCardCSPin = 12;
> 
>     pinMode( SDCardCSPin, OUTPUT );  // the SD library should take care of that.
>     if (!SD.begin( SDCardCSPin )) {
>       Serial.println("Card Mount Failed");
>     }
> ```
> 
> If it still doesn't work, you may try other values for SDCardCSPin (e.g. 15 is the hardware CS pin for SPI)
> 
> Where did you get those values from ?
> 
> ```
> #define SD_CS 12
> #define SD_MOSI 23
> #define SD_MISO 2
> #define SD_SCK 18
> ```
> 
> MOSI/MISO/SCK seem to have standard values, but any TTGO example I've found uses 15 for SD_CS, maybe this pinout is for another variant of the TTGO-T8 ?
> 
> Anyway, see how [this worked](https://forum.arduino.cc/index.php?topic=594910.0) with a different model of yours, the pin numbers may be different but the logical approach to find the pins is valid.
> 
> Happy hacking !

Thanks for your help, I will test as you said

**Comment by LuckyFishGeek** [comment]
@tobozo @justcallmekoko 
Re-wired according to what you just said, but the TF card still does not work
Keep asking for help
Thank you two friends for helping me
Below is my wiring and configuration diagram

![Snipaste_2020-10-22_19-39-23](https://user-images.githubusercontent.com/29472751/96867663-99587980-149f-11eb-94d1-22a7bb0a4f36.png)
![Snipaste_2020-10-22_19-45-43](https://user-images.githubusercontent.com/29472751/96867667-9a89a680-149f-11eb-8b06-8e3f357f9598.png)
![Snipaste_2020-10-22_19-45-51](https://user-images.githubusercontent.com/29472751/96867669-9b223d00-149f-11eb-820f-aa8840eb69b2.png)
![Snipaste_2020-10-22_19-47-12](https://user-images.githubusercontent.com/29472751/96867671-9bbad380-149f-11eb-80a4-35c042d478a7.png)

**Comment by justcallmekoko** [comment]
Are you still inserting the SD card into the slot on the TTGO or are you putting in in the slot behind the screen?

**Comment by LuckyFishGeek** [comment]
> Are you still inserting the SD card into the slot on the TTGO or are you putting in in the slot behind the screen?

Both methods have been tested and they don’t work

**Comment by LuckyFishGeek** [comment]
> Are you still inserting the SD card into the slot on the TTGO or are you putting in in the slot behind the screen?

I will check the line again today to see if the connection is wrong

**Comment by justcallmekoko** [comment]
If you use the SD slot behind the screen, I am confident the connection method [here](https://github.com/justcallmekoko/ESP32Marauder#connections) will work as long as you wire it accordingly. 

It looks like the pins in the I use for making the SD connection are still broken out on your TTGO board. This should work.

**Comment by LuckyFishGeek** [comment]
> If you use the SD slot behind the screen, I am confident the connection method [here](https://github.com/justcallmekoko/ESP32Marauder#connections) will work as long as you wire it accordingly.
> 
> It looks like the pins in the I use for making the SD connection are still broken out on your TTGO board. This should work.

According to your wiring method, I can read the SD card from the interface on the screen the first time

Can the SD card be read on TTGO T8 V1.3 after optimization?

Thank you again for your design

**Comment by justcallmekoko** [comment]
Yes but according to the diagram of the TTGO, the MISO, MOSI, SCK, and CS pins are different from what the marauder code expects. I am not sure how to to this, but you will need to specify those pins when calling `SD.begin()`

**Comment by tobozo** [comment]
@LuckyFishGeek can you please try this sketch with a SD inserted in the TTGO onboard SD Card reader ?

```C

#include <SD.h>

#define SD_SCLK  14
#define SD_MISO   2
#define SD_MOSI  15
#define SD_CS    13


SPIClass *sdhander = nullptr;

bool sdcard_begin()
{
  if (!sdhander) {
    sdhander = new SPIClass(HSPI);
    sdhander->begin(SD_SCLK, SD_MISO, SD_MOSI, SD_CS);
  }
  if (!SD.begin(SD_CS, *sdhander, 20000000)) { // default = 20MHz but capped by SPI at 16MHz
    log_e("SD Card Mount Failed");
    return false;
  }
  return true;
}

void setup()
{
  Serial.begin(115200);
  if( ! sdcard_begin() ) {
    Serial.println("Can't read SD Card, aborting");
    while(1);
  } else {
    Serial.println("SD Card success !!");
  }
}

void loop() { }

```

You will have to momentarily remove the wires from the TFT until you find out the correct pinout for the TTGO onboard SD card reader.

/!\ Make sure you perform a full power cycle after every change in the `#define` values

Only when the valid pinout is found, re-wire the TFT in order to check if the SD card is still detected.

If your SD card starts failing after that, it probably means there are pin conflicts between the TFT and the SD.

If your SD Card is still working, you can use the pinout in the ESPMarauder and start testing on this basis.

Random tip: make sure you've set the debug level to "warn" before flashing.

![image](https://user-images.githubusercontent.com/1893754/97002116-cbb6b500-1539-11eb-9c55-59fcfe54ed82.png)

**Comment by LuckyFishGeek** [comment]
> @LuckyFishGeek can you please try this sketch with a SD inserted in the TTGO onboard SD Card reader ?
> 
> ```c
> #include <SD.h>
> 
> #define SD_SCLK  14
> #define SD_MISO   2
> #define SD_MOSI  15
> #define SD_CS    13
> 
> 
> SPIClass *sdhander = nullptr;
> 
> bool sdcard_begin()
> {
>   if (!sdhander) {
>     sdhander = new SPIClass(HSPI);
>     sdhander->begin(SD_SCLK, SD_MISO, SD_MOSI, SD_CS);
>   }
>   if (!SD.begin(SD_CS, *sdhander, 20000000)) { // default = 20MHz but capped by SPI at 16MHz
>     log_e("SD Card Mount Failed");
>     return false;
>   }
>   return true;
> }
> 
> void setup()
> {
>   Serial.begin(115200);
>   if( ! sdcard_begin() ) {
>     Serial.println("Can't read SD Card, aborting");
>     while(1);
>   } else {
>     Serial.println("SD Card success !!");
>   }
> }
> 
> void loop() { }
> ```
> 
> You will have to momentarily remove the wires from the TFT until you find out the correct pinout for the TTGO onboard SD card reader.
> 
> /!\ Make sure you perform a full power cycle after every change in the `#define` values
> 
> Only when the valid pinout is found, re-wire the TFT in order to check if the SD card is still detected.
> 
> If your SD card starts failing after that, it probably means there are pin conflicts between the TFT and the SD.
> 
> If your SD Card is still working, you can use the pinout in the ESPMarauder and start testing on this basis.
> 
> Random tip: make sure you've set the debug level to "warn" before flashing.
> 
> ![image](https://user-images.githubusercontent.com/1893754/97002116-cbb6b500-1539-11eb-9c55-59fcfe54ed82.png)

Okay, I will test it tomorrow. It is already 8 o'clock on my side and I am lying in bed.  Thank you again for your enthusiastic help.  I will feedback the test results in time

**Comment by LuckyFishGeek** [comment]
> @LuckyFishGeek can you please try this sketch with a SD inserted in the TTGO onboard SD Card reader ?
> 
> ```c
> #include <SD.h>
> 
> #define SD_SCLK  14
> #define SD_MISO   2
> #define SD_MOSI  15
> #define SD_CS    13
> 
> 
> SPIClass *sdhander = nullptr;
> 
> bool sdcard_begin()
> {
>   if (!sdhander) {
>     sdhander = new SPIClass(HSPI);
>     sdhander->begin(SD_SCLK, SD_MISO, SD_MOSI, SD_CS);
>   }
>   if (!SD.begin(SD_CS, *sdhander, 20000000)) { // default = 20MHz but capped by SPI at 16MHz
>     log_e("SD Card Mount Failed");
>     return false;
>   }
>   return true;
> }
> 
> void setup()
> {
>   Serial.begin(115200);
>   if( ! sdcard_begin() ) {
>     Serial.println("Can't read SD Card, aborting");
>     while(1);
>   } else {
>     Serial.println("SD Card success !!");
>   }
> }
> 
> void loop() { }
> ```
> 
> You will have to momentarily remove the wires from the TFT until you find out the correct pinout for the TTGO onboard SD card reader.
> 
> /!\ Make sure you perform a full power cycle after every change in the `#define` values
> 
> Only when the valid pinout is found, re-wire the TFT in order to check if the SD card is still detected.
> 
> If your SD card starts failing after that, it probably means there are pin conflicts between the TFT and the SD.
> 
> If your SD Card is still working, you can use the pinout in the ESPMarauder and start testing on this basis.
> 
> Random tip: make sure you've set the debug level to "warn" before flashing.
> 
> ![image](https://user-images.githubusercontent.com/1893754/97002116-cbb6b500-1539-11eb-9c55-59fcfe54ed82.png)

![Snipaste_2020-10-25_15-12-43](https://user-images.githubusercontent.com/29472751/97101022-b2963b80-16d4-11eb-8409-40843bc2637d.png)
![beauty_20201025151302](https://user-images.githubusercontent.com/29472751/97101026-b75aef80-16d4-11eb-8a0d-6bf221040769.jpg)
After using your code, the SD card prompts success

The second picture is the pin diagram written on the board

**Comment by tobozo** [comment]
yay !

This pinout is from the documentation you provided earlier, it's using hardware SPI.

![image](https://user-images.githubusercontent.com/1893754/97105070-c2a02200-16b8-11eb-856a-e617ec74ad66.png)

Now see if this TFT pinout (taken from TFT_eSPI TTGO config) can coexist with your actual SD configuration, just wire the TFT to these pins, and check that the SD example sketch still detects your SD Card successfully : 

```
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS    5
#define TFT_DC    0
#define TFT_RST   4
#define TOUCH_CS 13
```

If so, you can use these settings with the ESP32 Marauder and go on your WiFi duties :-)

**Comment by LuckyFishGeek** [comment]
> yay !
> 
> This pinout is from the documentation you provided earlier, it's using hardware SPI.
> 
> ![image](https://user-images.githubusercontent.com/1893754/97105070-c2a02200-16b8-11eb-856a-e617ec74ad66.png)
> 
> Now see if this TFT pinout (taken from TFT_eSPI TTGO config) can coexist with your actual SD configuration, just wire the TFT to these pins, and check that the SD example sketch still detects your SD Card successfully :
> 
> ```
> #define TFT_MISO 19
> #define TFT_MOSI 23
> #define TFT_SCLK 18
> #define TFT_CS    5
> #define TFT_DC    0
> #define TFT_RST   4
> #define TOUCH_CS 13
> ```
> 
> If so, you can use these settings with the ESP32 Marauder and go on your WiFi duties :-)

Thank you for your kind help to me.  I will be going out a far door recently, and I will report the test results when I get home.  I wish you a happy life again

**Comment by LuckyFishGeek** [comment]
@tobozo 
![Snipaste_2020-10-27_12-43-29](https://user-images.githubusercontent.com/29472751/97257868-1a25c580-1852-11eb-9b15-65571d5acceb.png)
![beauty_20201027124302](https://user-images.githubusercontent.com/29472751/97257869-1b56f280-1852-11eb-8612-d7d3fb013953.jpg)
Seems to conflict

**Comment by LuckyFishGeek** [comment]
@tobozo 
![Snipaste_2020-10-27_12-46-58](https://user-images.githubusercontent.com/29472751/97258074-902a2c80-1852-11eb-8dbe-c5d9cf1c6c1e.png)

SD Card success !!

**Comment by justcallmekoko** [comment]
This might be a @tobozo question, but I am pretty confident definitions in the main file supersede definitions in header files. You should be good.

Worst case scenario, I am wrong and you just have to try again with modified values in the header file as well.

**Comment by LuckyFishGeek** [comment]
> This might be a @tobozo question, but I am pretty confident definitions in the main file supersede definitions in header files. You should be good.
> 
> Worst case scenario, I am wrong and you just have to try again with modified values in the header file as well.

Thanks for your kind help, I will test it tomorrow

**Comment by LuckyFishGeek** [comment]
@tobozo @justcallmekoko  
Still unable to mount the SD card

This is my setting. Can you help me see if my setting is wrong? Now the screen can’t display normally!
thanks。。
![Snipaste_2020-11-08_10-52-09](https://user-images.githubusercontent.com/29472751/98455836-cc458180-21b0-11eb-82ff-54be95423641.png)
![Snipaste_2020-11-08_10-55-01](https://user-images.githubusercontent.com/29472751/98455839-de272480-21b0-11eb-9a36-987c1f90fe89.png)

user_Setup.h    I am using the default configuration, do I need to modify this file to be the same as SDinterface.h?
![Snipaste_2020-11-08_10-55-40](https://user-images.githubusercontent.com/29472751/98455865-1fb7cf80-21b1-11eb-83a6-57363b69f851.png)

![beauty_20201108105227](https://user-images.githubusercontent.com/29472751/98455870-32320900-21b1-11eb-9f93-dc30803769c9.jpg)

**Comment by tobozo** [comment]
in your configuration SD_CS and TOUCH_CS are using the same pin, this is wrong.

![image](https://user-images.githubusercontent.com/1893754/98463204-eafc4600-21b9-11eb-9b93-146d3500c639.png)


Can you try to assign TOUCH_CS to a *free* pin ?

Also where is your User_Setup.h file ? is it still in ESPMarauder folder or did you overwrite the file in TFT_eSPI library folder as you're supposed to ?

**Comment by LuckyFishGeek** [comment]
@tobozo I modified C:\Users\Administrator\Documents\Arduino\libraries\TFT_eSPI-master\User_Setup.h
![Snipaste_2020-11-09_10-15-57](https://user-images.githubusercontent.com/29472751/98493088-923db380-2274-11eb-8197-6e75ba0523a5.png)
Also modified
![Snipaste_2020-11-09_10-13-36](https://user-images.githubusercontent.com/29472751/98493118-a08bcf80-2274-11eb-8a2f-3cf14c629c23.png)
  not work
![Snipaste_2020-11-09_10-17-02](https://user-images.githubusercontent.com/29472751/98493410-56efb480-2275-11eb-9354-5ce00c998ab3.png)
![beauty_20201109102052](https://user-images.githubusercontent.com/29472751/98493427-5eaf5900-2275-11eb-8589-4b5400d16acb.jpg)
Thank you again for your help

**Comment by tobozo** [comment]
TFT_RST (pin 12) is already used by the SD Card (data port), so you need to move this TFT_RST one to another free pin

![image](https://user-images.githubusercontent.com/1893754/98527248-12ffae00-227b-11eb-8083-b9c74b755664.png)

**Comment by LuckyFishGeek** [comment]
![Snipaste_2020-11-09_18-36-54](https://user-images.githubusercontent.com/29472751/98531091-cb991200-22ba-11eb-8d82-64baaa055008.png)

Synchronously modified C:\Users\Administrator\Documents\Arduino\libraries\TFT_eSPI-master\User_Setup.h
![Snipaste_2020-11-09_18-37-28](https://user-images.githubusercontent.com/29472751/98531098-ccca3f00-22ba-11eb-8892-4666119449a8.png)

It can be displayed correctly, but the SD card still cannot be mounted!
This question is really stubborn. Haha
![beauty_20201109183613](https://user-images.githubusercontent.com/29472751/98531289-16b32500-22bb-11eb-8aad-e7ba74dad5c6.jpg)
About SD card
I tried the 16G and 1G capacity of SanDisk brand
Format to FAT32

All show failed to mount
@tobozo

**Comment by tobozo** [comment]
test : 

- unplug the TFT Wires one after the other until the SD Card works
- when the SD works : you found the conflicting pin !

**Comment by LuckyFishGeek** [comment]
> test :
> 
> * unplug the TFT Wires one after the other until the SD Card works
> * when the SD works : you found the conflicting pin !

@tobozo 
It's weird. I tested it as you said, every time I unplug a pin and a wire, I restart it! Then see if the SD card is mounted!
As a result, all the pins have been tested, and the SD card prompts that it cannot be mounted!

**Comment by tobozo** [comment]
> I unplug a pin and a wire (...) Then see if the SD card is mounted!

>  all the pins have been tested, and the SD card prompts that it cannot be mounted!

Those are conflicting informations.

- when does it mount, and when does it not mount ?
- how many TFT pins are unplugged when the SD card mounts successfully, and which are they ?

Please be methodic and specific otherwise I can't provide you with efficient help.

**Comment by LuckyFishGeek** [comment]
@tobozo 
Maybe I have a problem with the previous expression, sorry
My operation is as follows: Unplug the pins on the TFT screen one by one, and every time I unplug a pin, I will restart once to see if the SD card is successfully mounted
CS
RESET
D/C
MOSI
SCK
led
MISO
T_CLK
T_CS
T_DI
T_DO

![Uploading beauty_20201110202224.jpg…]()
![Uploading Snipaste_2020-11-10_20-24-25.png…]()
Just like this, I now unplug the TFT_CS pin, then I click reset and check if the SD card is mounted!
Is my test method correct? Or do you need to unplug all the TFT screen pins at once?

**Comment by tobozo** [comment]
Thanks for this feedback, it sounds like you're very close :-)

Some thoughts:

The message `IP5306 I2C supported: false` means some Wire.begin() occured, which you probably don't want. 
From the BatteryInterface.h file: 

    #define I2C_SDA 33
    #define I2C_SCL 22

You can eventually comment out this line in the .ino file to make sure this is not interferring with the TFT:

    // battery_obj.RunSetup();

**Comment by LuckyFishGeek** [comment]
@tobozo 
Good morning I'm only 10 am here, I don't know what time it is over there, haha

According to what you said, I commented out this, after re-flashing the firmware, the same error still appeared
![Snipaste_2020-11-11_10-11-04](https://user-images.githubusercontent.com/29472751/98756998-8eda3180-2406-11eb-8bf5-d0f764d40bdd.png)

**Comment by tobozo** [comment]
Well that's the difference between "helping" and "assisting", providing some methodologies, not solutions.

I'm sure you'll eventually find the correct pins combination by yourself, happy hacking !
