### ISSUE TITLE
ESP32 new board

### ISSUE THREAD

**Issue by BragaBoss** [justcallmekoko/ESP32Marauder#590]
![IMG_20241014_131140](https://github.com/user-attachments/assets/3f380303-2797-4c55-bad3-ddf6f51031ab)
 ![IMG_20241014_131126](https://github.com/user-attachments/assets/e19d8715-ff22-4cd0-9b7f-017e198a0d00)

Has anyone made a marauder on such a board?

**Comment by Mantas22XYT** [comment]
Yes, use this repo: https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display

**Comment by Fr4nkFletcher** [comment]
@BragaBoss on it. just waiting for the module to arrive

**Comment by Fr4nkFletcher** [comment]
@BragaBoss added to the webflasher [here](https://fr4nkfletcher.github.io/Adafruit_WebSerial_ESPTool/)
