### ISSUE TITLE
Add support ESP32-2432S024

### ISSUE THREAD

**Issue by krisss117** [justcallmekoko/ESP32Marauder#594]
Please add suppotr for ESP32-2432S024. Formware from https://github.com/b00mekk/ESP32Marauder_ESP32-2432S024R_CYD/tree/main work, but when power on, then few times reboot during boot, then work fine.

**Comment by BlushTTV** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display

**Comment by krisss117** [comment]
Thanks :)
