### ISSUE TITLE
And really we can trade. Send me the etsy knock off and I will send you a real v6. If I can fix the etsy knock off, I will send it back to you and you can just keep both

### ISSUE THREAD

**Issue by S3real-ux** [justcallmekoko/ESP32Marauder#596]
And really we can trade. Send me the etsy knock off and I will send you a real v6. If I can fix the etsy knock off, I will send it back to you and you can just keep both

_Originally posted by @justcallmekoko in https://github.com/justcallmekoko/ESP32Marauder/issues/595#issuecomment-2442882659_
            
how could we do that?. and also i relly need help, theyr making me pay for the debugger and they said i need to take action for the mistakes i did.

**Comment by justcallmekoko** [comment]
What country are you located in?

**Comment by S3real-ux** [comment]
im located in switzerland, pretty near of france and germany.

**Comment by S3real-ux** [comment]
is it possible we talk through discord pm? it would be easier for me, its up to you tho i dont really mind. ive sent you some stuff there already

**Comment by justcallmekoko** [comment]
Discord is find. Shoot me a DM

**Comment by S3real-ux** [comment]
hey, ive sent you the adress via discord

**Comment by S3real-ux** [comment]
Are you still up for the trade? Just making sure so it's not there and I leave it there thinking it's not arrived yet. Please answer if you see this

**Comment by RaoufiTech** [comment]
@S3real-ux hi sorry to say but [justcallmekoko](https://github.com/justcallmekoko) is no longer with us 🕊️

**Comment by justcallmekoko** [comment]
resolved via dms
