### ISSUE TITLE
Is correcting the compiler error still a part of the flashing process?

### ISSUE THREAD

**Issue by Ahorrorfilm** [justcallmekoko/ESP32Marauder#6]
https://github.com/justcallmekoko/ESP32Marauder/issues/2#issuecomment-555695918

**Comment by justcallmekoko** [comment]
It isn't an error with the compiler. It is an extension of the TFT_eSPI library that has to be made in order to get the buttons lined up properly. But the referenced issue is still part of the process

**Comment by Ahorrorfilm** [comment]
Okay gotcha, thanks! Does that need to be done with a text editor before its added as a library? Having trouble editing after it's already added. Sorry, this is my first time messing with arduino/esp32 stuff..

**Comment by justcallmekoko** [comment]
It can be done before or after. It should not matter. 
If you want to do it before, then you can.
If you want to wait until you have installed the library and just traverse the Arduino directories and modify it there.

**Comment by Ahorrorfilm** [comment]
okay word, thanks for being chill also.

**Comment by justcallmekoko** [comment]
No problem. Let me know if you have any other questions.
