### ISSUE TITLE
Esp32 Marauder

### ISSUE THREAD

**Issue by ManiaAndrei** [justcallmekoko/ESP32Marauder#75]
Hello! I have a question about the Esp32 Marauder. In my city, i don.t find a 2.8" display just 2.4" with the SPFD5408 controller(it says that the controller is compatibile with ILI9341). My question: is this display good? The display link is https://contactelectric.ro/display/1716-shield-compatibil-arduino-lcd-rosu-de-24-cu. Please help me!

**Comment by justcallmekoko** [comment]
The display will not work. The marauder firmware is designed specifically to work with...
- 2.8" display
- ILI9241
- XPT2046 touch controller

The display you have sent does not satisfy these requirements. For single screen orders like these, I order from amazon. Are you able to order from amazon in romania?
