### ISSUE TITLE
how to run this in a odroid go?

### ISSUE THREAD

**Issue by ankris812** [justcallmekoko/ESP32Marauder#76]
can run this in odroid go? it dont have a touchscreen

**Comment by justcallmekoko** [comment]
The repository in its current state is not configured to run on the odroid go. Someone has managed to make it work but it involves heavy modification to the firmware to make it work with the different screen and button inputs

**Comment by ankris812** [comment]
do you know where?

**Comment by justcallmekoko** [comment]
I am not sure. I received a picture of it but it was someone telling me they found it somewhere.

**Comment by justcallmekoko** [comment]
The odroid go does not have a touch screen correct?

**Comment by ankris812** [comment]
exactly, is with buttons

**Comment by justcallmekoko** [comment]
You will have to create the functionality to control the Marauder with buttons instead of touch screen

**Comment by ankris812** [comment]
ok, thanks
