### ISSUE TITLE
Display.h:7:25: fatal error: JPEGDecoder.h: No such file or directory

### ISSUE THREAD

**Issue by xcs011** [justcallmekoko/ESP32Marauder#78]
I keep getting this error when I try to verify the sketch, and it doesnt appear to be in either library,
After doing a little searching, the mentioned file is not in the source code, or either prerequisite library. 
I appreciate any help you can give, thank you.

**Comment by xcs011** [comment]
Ive also realized I have a hiletgo esp32-wroom, not a lolin, and cant find it in the board manager, although that isnt a problem with verification.

**Comment by justcallmekoko** [comment]
This is my mistake. I did not document as I went along and there are a lot of steps I had forgotten about which are required to setup the dev environment.

You have to install [this library](https://github.com/Bodmer/JPEGDecoder). This should solve your issue. The ESP32 board should not matter. The main concern is that the board you select in the IDE must include the partition scheme to allow for large app and small spiffs.

Let me know if this resolves you issue.

**Comment by xcs011** [comment]
That worked, thank you, the only two other errors I had were for linkedlist, and lvgl, but they were easily installed from the library manager.

**Comment by xcs011** [comment]
lvhl appears to be fixed after configuring it, but I might have installed a bare bones arduino client or something, because im also misssing arduinojson.h

**Comment by xcs011** [comment]
list of missing libraries for all interested:
lvgl
linkedlist
adafruit neopixel
arduinojson 5
nimblearduino

**Comment by justcallmekoko** [comment]
Don't install lvgl. Install lv_arduino instead.

**Comment by xcs011** [comment]
Thank you, the only two other errors I had were no set_touch, and out of space, but viewing closed issues helped, so now it compiles.
I will breadboard it and test it out.

**Comment by justcallmekoko** [comment]
Awesome. Glad to hear you got it working. Post pictures when you get it put together. I would love to see it
