### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x00) SPIFFS Upload failed!

### ISSUE THREAD

**Issue by xcs011** [justcallmekoko/ESP32Marauder#79]
SPIFFS keeps giving me this error upon upload.
My setup uses an external SD shield, connected to power and the necessary pinout pins, would this be solved by using the sd reader inside the display instead?

**Comment by xcs011** [comment]
Asking instead of testing because I want to be sure before I go soldering anything

**Comment by justcallmekoko** [comment]
I would use the SD reader in the display to keep it as consistent with the original design as possible. The SD configuration should not have anything to do with SPIFFS though

**Comment by xcs011** [comment]
After searching around, neither grounding pin 0, or entering flash mode via onboard buttons works.

**Comment by xcs011** [comment]
Trying to erase_flash with esptool cant connect either, I think something may be wrong with my board.

**Comment by xcs011** [comment]
If I end up having to buy a new board, would you have any suggestions?

**Comment by justcallmekoko** [comment]
Something simple like a ESP32 NodeMCU would be just fine.

**Comment by justcallmekoko** [comment]
any progress?

**Comment by xcs011** [comment]
The replacement board I ordered never came, im going to have to order another.

**Comment by justcallmekoko** [comment]
Oh wow where did you order from?

**Comment by xcs011** [comment]
I had ordered from PMD way, which had originally said it was shipping from Canada, then the tracking info showed China, and despite tracking saying it was delivered, it never came.

**Comment by justcallmekoko** [comment]
What country are you in?

**Comment by xcs011** [comment]
The United States

**Comment by justcallmekoko** [comment]
Why not order from amazon?

**Comment by xcs011** [comment]
It was an original d32, figured id go with it just to be safe, and still half the price.

**Comment by justcallmekoko** [comment]
Let me know when you make some progress on this. I have been in contact with someone who managed to get this working with an ordinary ESP32 development board.

**Comment by xcs011** [comment]
I know I havent posted in a while, I was busy with job searching, but I got a feather32 and will try again over the next few days.

**Comment by xcs011** [comment]
I also realized this entire thing was my fault, I plugged it in upside down the first time and fried it because I wasn't paying attention.

**Comment by xcs011** [comment]
I appear to have gone 1 step forward 2 steps back however, as now it just times out waiting for a packet header.

**Comment by justcallmekoko** [comment]
Are you using the Arduino IDE for this or are you using esptool on command line?

**Comment by xcs011** [comment]
I am using the arduino ide set up as in the guide.

**Comment by justcallmekoko** [comment]
Can you provide a screenshot of the IDE output when you try to flash the firmware. Can you also send a picture of the ESP32 development board you are using?

**Comment by xcs011** [comment]
I'm sorry I have been very busy job searching over the last few days and will re-open this when I have time.
