### ISSUE TITLE
scan for access points but also clients connected to them

### ISSUE THREAD

**Issue by Slinkydude** [justcallmekoko/ESP32Marauder#84]
Hi is it possible to add capability to not only scan for access points but also clients connected to them like in video from Null Byte - Use Kismet to Find & Monitor Nearby Wi-Fi Devices [Tutorial]

 https://www.youtube.com/watch?v=3v_bwtHIToQ&t=316s

**Comment by justcallmekoko** [comment]
I can make something that can detect clients and which APs they are connected to but I will probably not include vendor MACs. I do not have enough space in the ESP32 for all of those lists.

**Comment by justcallmekoko** [comment]
Implemented in v0.10.0
