### ISSUE TITLE
m5stack core 2 which ESP32Marauder Version?

### ISSUE THREAD

**Issue by Icesoldier7** [justcallmekoko/ESP32Marauder#96]
Hello, which Version of the ESP32Marauder can i use for a m5stack core 2? 

Thanks for the help :)

**Comment by justcallmekoko** [comment]
There are currently no versions of the ESP32 Marauder firmware that work for the m5stack core 2 out of the gate. It would require some modification of the code to adjust screen resolution and you would need to specify the screen driver in the TFT-eSPI library
