### ISSUE TITLE
compilation error ieee80211_raw_frame_sanity_check

### ISSUE THREAD

**Issue by superjasiek** [justcallmekoko/ESP32Marauder#97]
Unfortunately i'm not able to compile your code. Same error on pc and raspberry pi:
```
ArduinoData\packages\esp32\hardware\esp32\1.0.5/tools/sdk/lib\libnet80211.a(ieee80211_output.o): In function `ieee80211_raw_frame_sanity_check':
(.text.ieee80211_raw_frame_sanity_check+0x64): multiple definition of `ieee80211_raw_frame_sanity_check'
sketch\objs.a(WiFiScan.cpp.o):...\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantAsImpl.hpp:40: first defined here
collect2.exe: error: ld returned 1 exit status
```
could not find any solution. 
I will be grateful for any advice.
Take care,
Jan

**Comment by justcallmekoko** [comment]
If you are using the Arduino IDE, you need to make sure you follow [these instructions](https://github.com/justcallmekoko/ESP32Marauder/wiki/arduino-ide-setup) when setting it up.

Specifically you need to make sure you have Arduino ESP32 v2.0.0 installed and you need to use the compiler flag that allows for multiple definition of a function. That last one is specifically what is causing the error you referenced above.
